name: Setup Branch Protection

on:
  workflow_dispatch:
    inputs:
      setup_protection:
        description: 'Setup branch protection for main'
        required: false
        default: 'true'

permissions:
  contents: read

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_protection == 'true'
    
    steps:
    - name: Setup branch protection for main
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const { data: protection } = await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['test', 'quality-checks']
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                require_last_push_approval: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
            console.log('✅ Branch protection rules set for main branch');
            console.log('Protection settings:', protection);
            
            // Also protect release branch if it exists
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'release',
                required_status_checks: {
                  strict: true,
                  contexts: ['test']
                },
                enforce_admins: false,
                required_pull_request_reviews: null,
                restrictions: null,
                allow_force_pushes: true,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: false
              });
              console.log('✅ Basic protection set for release branch');
            } catch (error) {
              console.log('ℹ️ Release branch protection not set (branch may not exist yet)');
            }
            
          } catch (error) {
            console.error('❌ Failed to set branch protection:', error.message);
            
            // Provide manual setup instructions
            console.log(`
            ## Manual Branch Protection Setup Required
            
            Please manually configure branch protection for the 'main' branch:
            
            1. Go to: https://github.com/${context.repo.owner}/${context.repo.repo}/settings/branches
            2. Click "Add rule" for the main branch
            3. Enable the following settings:
               ✅ Require a pull request before merging
               ✅ Require approvals (1)
               ✅ Dismiss stale PR approvals when new commits are pushed
               ✅ Require status checks to pass before merging
               ✅ Require branches to be up to date before merging
               ✅ Require conversation resolution before merging
               ❌ Do not allow bypassing the above settings
               ❌ Restrict pushes that create files
               ❌ Allow force pushes
               ❌ Allow deletions
            
            Required status checks:
            - test
            - quality-checks
            
            This will ensure main branch is protected and releases go through proper review process.
            `);
          }
